import { useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowRight, Award, BookOpen, BriefcaseBusiness, Check, ChevronDown, CircleHelp, FileText, Gauge, GraduationCap, LayoutDashboard, LogOut, MapPin, Pencil, Plus, Search, Settings2, ShieldCheck, Sparkles, Target, TrendingUp, UploadCloud, UserRound, X } from 'lucide-react'
import { StudentRecommendations } from './RecommendationDashboard.jsx'
import './student.css'

const roleOptions = ['Data Analyst', 'Cloud Support Associate', 'Product Designer', 'Full-stack Developer']
const skillSeed = [{ name: 'SQL', level: 82, demand: 'Critical', color: 'coral' }, { name: 'Python', level: 68, demand: 'High', color: 'mint' }, { name: 'Power BI', level: 54, demand: 'High', color: 'blue' }, { name: 'Data storytelling', level: 34, demand: 'Medium', color: 'yellow' }]
const progressData = [{ week: 'W1', score: 51 }, { week: 'W2', score: 56 }, { week: 'W3', score: 61 }, { week: 'W4', score: 64 }, { week: 'W5', score: 68 }, { week: 'W6', score: 72 }]
const recommendations = [{ icon: BookOpen, title: 'SQL for Data Analysis', meta: '12 hours · Beginner to Advanced', reason: 'Closes your highest priority gap', tone: 'coral' }, { icon: TrendingUp, title: 'Tell better stories with data', meta: '6 hours · Intermediate', reason: 'A fast path to +9 readiness points', tone: 'mint' }, { icon: ShieldCheck, title: 'Power BI Dashboard Lab', meta: '8 hours · Intermediate', reason: 'Requested in 72% of target roles', tone: 'blue' }]

export default function StudentDashboard() {
  const [activeTab, setActiveTab] = useState('Dashboard')
  const [targetRole, setTargetRole] = useState('Data Analyst')
  const [skills, setSkills] = useState(skillSeed)
  const [showResume, setShowResume] = useState(false)
  const [showProfile, setShowProfile] = useState(false)
  const [resumeName, setResumeName] = useState('')
  const [completed, setCompleted] = useState([1])
  const { register, handleSubmit } = useForm({ defaultValues: { name: 'Arjun Kulkarni', location: 'Pune, Maharashtra', headline: 'Aspiring data analyst' } })
  const readiness = useMemo(() => Math.round(skills.reduce((sum, skill) => sum + skill.level, 0) / skills.length), [skills])

  const updateSkill = (name, level) => setSkills((current) => current.map((skill) => skill.name === name ? { ...skill, level: Number(level) } : skill))
  const saveProfile = (values) => { localStorage.setItem('skillsync-student-profile', JSON.stringify(values)); setShowProfile(false) }

  return <div className="student-shell">
    <aside className="student-sidebar"><div className="student-brand"><span className="student-brand-mark"><Sparkles size={16} /></span><strong>Skill<span>Sync</span></strong></div><div className="student-profile-mini"><div className="student-avatar">AK</div><div><strong>Arjun Kulkarni</strong><small>Learner workspace</small></div><ChevronDown size={14} /></div><p className="student-nav-label">My journey</p><nav className="student-nav">{[[LayoutDashboard, 'Dashboard'], [UserRound, 'My profile'], [Target, 'Skill gap'], [BookOpen, 'Recommendations'], [GraduationCap, 'Learning roadmap'], [Award, 'Assessments']].map(([Icon, label]) => <button className={activeTab === label ? 'selected' : ''} onClick={() => setActiveTab(label)} key={label}><Icon size={16} /><span>{label}</span>{label === 'Skill gap' && <em>4</em>}</button>)}</nav><div className="student-side-bottom"><button className="student-side-link"><Settings2 size={16} /> Settings</button><button className="student-side-link"><CircleHelp size={16} /> Help centre</button><button className="student-logout" onClick={() => { localStorage.removeItem('skillsync-session'); window.location.href = '/login' }}><LogOut size={16} /> Sign out</button></div></aside>
    <main className="student-main"><header className="student-topbar"><div><span className="student-breadcrumb">Learner workspace</span><span className="student-slash">/</span><strong>{activeTab}</strong></div><div className="student-top-actions"><button aria-label="Search"><Search size={17} /></button><button aria-label="Notifications"><span className="notification-dot" /><Award size={17} /></button><button className="student-top-avatar">AK</button></div></header>
      <div className="student-content">
        {activeTab === 'Recommendations' ? (
          <StudentRecommendations onOpenRoadmap={() => setActiveTab('Learning roadmap')} />
        ) : (<section className="student-welcome"><div><p className="student-kicker">YOUR NEXT OPPORTUNITY</p><h1>Keep building, Arjun <span>✦</span></h1><p>Here is the clearest path from your skills today to your target role.</p></div><button className="student-outline-button" onClick={() => setShowProfile(true)}><Pencil size={15} /> Edit profile</button></section>
        <section className="target-role-card"><div className="target-role-icon"><BriefcaseBusiness size={21} /></div><div className="target-role-copy"><p className="student-kicker">TARGET ROLE</p><strong>{targetRole}</strong><span>Based on 1,842 live opportunities in Maharashtra</span></div><div className="role-picker"><select value={targetRole} onChange={(event) => setTargetRole(event.target.value)}>{roleOptions.map((role) => <option key={role}>{role}</option>)}</select><ChevronDown size={14} /></div></section>
        <section className="student-stat-grid"><StudentStat icon={Gauge} label="Job readiness" value={`${readiness}%`} note="+8 pts this month" tone="violet" /><StudentStat icon={Target} label="Skills to strengthen" value="4" note="2 are critical" tone="coral" /><StudentStat icon={BookOpen} label="Learning progress" value="38%" note="3 of 8 modules" tone="mint" /><StudentStat icon={Award} label="Assessments" value="6" note="Next due in 4 days" tone="yellow" /></section>
        <div className="student-section-title"><div><p className="student-kicker">YOUR SIGNALS</p><h2>Readiness at a glance</h2></div><button className="student-text-button" onClick={() => setActiveTab('Skill gap')}>Open full analysis <ArrowRight size={14} /></button></div>
        <section className="student-grid-two"><div className="student-panel readiness-panel"><PanelHeading icon={TrendingUp} title="Job readiness score" action="How it is calculated" /><div className="readiness-body"><div className="score-ring" style={{ '--score': `${readiness * 3.6}deg` }}><div><strong>{readiness}%</strong><span>Ready to grow</span></div></div><div className="readiness-copy"><strong>{readiness >= 70 ? 'You are on a strong track.' : 'You are making steady progress.'}</strong><p>Your score combines assessed skill levels, target-role demand, and learning momentum.</p><div className="score-change"><TrendingUp size={14} /> <b>+8 points</b> since your last assessment</div></div></div><div className="mini-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={progressData}><defs><linearGradient id="studentScore" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7160e0" stopOpacity=".25" /><stop offset="100%" stopColor="#7160e0" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="week" hide /><YAxis hide domain={[40, 80]} /><Tooltip contentStyle={{ borderRadius: 8, border: '1px solid #e5e3ef', fontSize: 10 }} /><Area type="monotone" dataKey="score" stroke="#7160e0" strokeWidth={2} fill="url(#studentScore)" /></AreaChart></ResponsiveContainer></div></div>
          <div className="student-panel gaps-student-panel"><PanelHeading icon={Target} title="Your priority gaps" action="See all 4" /><p className="student-muted">Skills employers ask for that need your attention next.</p><div className="student-gap-list">{skills.map((skill) => <div className="student-gap-row" key={skill.name}><div className="gap-row-label"><span className={`student-skill-dot ${skill.color}`} /><strong>{skill.name}</strong><em>{skill.demand}</em></div><div className="gap-progress"><span style={{ width: `${skill.level}%` }} className={skill.color} /><i style={{ left: `${skill.level}%` }} /></div><div className="gap-row-foot"><span>Your level {skill.level}%</span><b>Role demand {skill.name === 'SQL' ? '90' : '78'}%</b></div></div>)}</div><button className="student-plan-button" onClick={() => setActiveTab('Learning roadmap')}>Build my learning plan <ArrowRight size={15} /></button></div></section>
        <div className="student-section-title compact"><div><p className="student-kicker">MAKE YOUR NEXT MOVE</p><h2>Recommended for you</h2></div><button className="student-text-button" onClick={() => setActiveTab('Recommendations')}>View all <ArrowRight size={14} /></button></div>
        <section className="recommendation-grid">{recommendations.map((item) => { const Icon = item.icon; return <button className="recommendation-card" key={item.title} onClick={() => setActiveTab('Learning roadmap')}><div className={`recommendation-icon ${item.tone}`}><Icon size={18} /></div><strong>{item.title}</strong><span>{item.meta}</span><small><Sparkles size={11} /> {item.reason}</small><ArrowRight className="recommendation-arrow" size={16} /></button> })}</section>
        <section className="roadmap-card"><div className="roadmap-head"><div><p className="student-kicker">PERSONALIZED ROADMAP</p><h2>Data Analyst launchpad</h2><p>Next milestone: demonstrate a complete analysis in your portfolio.</p></div><button className="student-outline-button" onClick={() => setActiveTab('Learning roadmap')}>Open roadmap <ArrowRight size={14} /></button></div><div className="roadmap-track">{['Baseline assessment', 'SQL foundations', 'Dashboard project', 'Portfolio review'].map((step, index) => <button className={`roadmap-step ${completed.includes(index) ? 'done' : ''}`} key={step} onClick={() => setCompleted((current) => current.includes(index) ? current : [...current, index])}><span>{completed.includes(index) ? <Check size={14} /> : index + 1}</span><strong>{step}</strong><small>{completed.includes(index) ? 'Completed' : index === 1 ? 'In progress' : 'Up next'}</small></button>)}</div></section>
        <section className="student-footer-row"><div><ShieldCheck size={17} /><span>Your profile is visible only to you and your approved learning partners.</span></div><span>Last synced 6 minutes ago</span></section>
        )}
      </div>
    </main>
    {showResume && <div className="student-modal-backdrop" onClick={() => setShowResume(false)}><div className="student-modal" onClick={(event) => event.stopPropagation()}><button className="student-modal-close" onClick={() => setShowResume(false)}><X size={17} /></button><div className="modal-top-icon"><UploadCloud size={21} /></div><p className="student-kicker">RESUME INTELLIGENCE</p><h2>Let your resume update your skills</h2><p>We will extract skills, experience signals, and evidence to refresh your profile.</p><label className="resume-drop"><input type="file" accept=".pdf,.doc,.docx" onChange={(event) => setResumeName(event.target.files?.[0]?.name || '')} /><UploadCloud size={25} /><strong>{resumeName || 'Choose your resume'}</strong><span>PDF or DOCX · up to 10 MB</span></label><button className="student-primary-button" disabled={!resumeName} onClick={() => setShowResume(false)}>Extract my skills <Sparkles size={15} /></button></div></div>}
    {showProfile && <div className="student-modal-backdrop" onClick={() => setShowProfile(false)}><form className="student-modal profile-modal" onClick={(event) => event.stopPropagation()} onSubmit={handleSubmit(saveProfile)}><button type="button" className="student-modal-close" onClick={() => setShowProfile(false)}><X size={17} /></button><div className="modal-top-icon"><UserRound size={21} /></div><p className="student-kicker">MY PROFILE</p><h2>Keep your learner profile current</h2><label className="student-form-label">Name<input {...register('name')} /></label><label className="student-form-label">Location<input {...register('location')} /></label><label className="student-form-label">Headline<input {...register('headline')} /></label><button className="student-primary-button" type="submit">Save profile <Check size={15} /></button></form></div>}
  </div>
}

function StudentStat({ icon: Icon, label, value, note, tone }) { return <div className="student-stat"><span className={`student-stat-icon ${tone}`}><Icon size={17} /></span><small>{label}</small><strong>{value}</strong><em>{note}</em></div> }
function PanelHeading({ icon: Icon, title, action }) { return <div className="student-panel-heading"><div><Icon size={17} /><h3>{title}</h3></div><button>{action}<ArrowRight size={12} /></button></div> }
